### ISSUE TITLE
[UA] Contact & Hours component on the Home Page

### ISSUE THREAD

**Issue by OliviaLiu417** [ChangePlusPlusVandy/MotherToMother#130]

**Comment by RachaelM13** [comment]
Added the UI for the Contact & Hours accordion. Edited the ContactUsAccordion.tsx file and added the CustomSVGContactUsAccordion.tsx. This file contains all icons from the figma as export functions which are called in the ContactUsAccordion.tsx file for better code readability. 

![Image](https://github.com/ChangePlusPlusVandy/MotherToMother/assets/115118738/a1c40efc-99bb-4df9-a5f5-9d1177282b4b)
