### ISSUE TITLE
[UA] Fix login page picture overlapping

### ISSUE THREAD

**Issue by OliviaLiu417** [ChangePlusPlusVandy/MotherToMother#142]
![Image](https://github.com/ChangePlusPlusVandy/MotherToMother/assets/81684017/74b7c356-9ece-46c8-9fea-ba6d6cb876a8)

**Comment by joseph-zou** [comment]
Do you want it as : 
<img width="197" alt="image" src="https://github.com/ChangePlusPlusVandy/MotherToMother/assets/53624798/a8c67084-a133-41aa-bf5f-bf0c892bb1e2">

or do you want it as 

<img width="199" alt="image" src="https://github.com/ChangePlusPlusVandy/MotherToMother/assets/53624798/c326b6bb-919a-4c50-bae6-6640ada92821">

@OliviaLiu417

**Comment by OliviaLiu417** [comment]
The first picture, thanks!

> Do you want it as : <img alt="image" width="197" src="https://private-user-images.githubusercontent.com/53624798/298753312-a8c67084-a133-41aa-bf5f-bf0c892bb1e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMzM0MzYsIm5iZiI6MTcwNjAzMzEzNiwicGF0aCI6Ii81MzYyNDc5OC8yOTg3NTMzMTItYThjNjcwODQtYTEzMy00MWFhLWJmNWYtYmYwYzg5MmJiMWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE4MDUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5ZmU4YzZhNzhkODkzYzEzYmRmYWVlNDM3MGZjNDM3NmM4YmQ1YTU3NjJhN2I4YTkyODJjZjM1NmU0MDQ1YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uzQzhrgsvKALaYA_HVhuYmlyMnVk0t5GrdtewEJCpuM">
> 
> or do you want it as
> 
> <img alt="image" width="199" src="https://private-user-images.githubusercontent.com/53624798/298753467-c326b6bb-919a-4c50-bae6-6640ada92821.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMzM0MzYsIm5iZiI6MTcwNjAzMzEzNiwicGF0aCI6Ii81MzYyNDc5OC8yOTg3NTM0NjctYzMyNmI2YmItOTE5YS00YzUwLWJhZTYtNjY0MGFkYTkyODIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE4MDUzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiZGNhYWIzMzJmMzUwMWIzNDFjNGU3NDM4Yzc0MzM4MjAzNDVlODA0ZTIwZDE3YWJkNGNlYjVlNWViYmMzMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fCGdx8kHKSWAtuGy4yBRW-ry4qp7nnpqQRJSViIZkWs">
> [@OliviaLiu417](https://github.com/OliviaLiu417)
