### ISSUE TITLE
Consolidate Form components on Frontend

### ISSUE THREAD

**Issue by OliviaLiu417** [ChangePlusPlusVandy/MotherToMother#23]

**Comment by RachaelM13** [comment]
![Screenshot 2023-11-06 211120](https://github.com/ChangePlusPlusVandy/MotherToMother/assets/115118738/3e1f9d82-7b8a-4c89-bdb5-5c64f6e8cd39)

![Screenshot 2023-11-06 211907](https://github.com/ChangePlusPlusVandy/MotherToMother/assets/115118738/128f5984-80c2-4cd9-8376-19741be9d0c5)

Not complete, however, combined the first section of the form with the second section.
