### ISSUE TITLE
Review component skeleton

### ISSUE THREAD

**Issue by OliviaLiu417** [ChangePlusPlusVandy/MotherToMother#9]
Finish the review component in the form process in the Figma Design

**Comment by Kaleab-A** [comment]
Where should I access the Figma Design? I am new to working with Figma.

**Comment by OliviaLiu417** [comment]
https://www.figma.com/file/ATWZcoHVhhRC5XJjs2Rv1n?embed_host=notion&kind=&mode=design&node-id=0-1&type=design&viewer=1
Also all project related info can be found in our Notion page, including design and dev spec.
